# Pandas

In [1]:
# Build on Top of Numpy
# Used for Data Manipulating, Data Cleaning, Data Preprocessing etc.

In [1]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

# Pandas (Series)

In [4]:
A = pd.Series([1,2,3,4],index=['a','b','c','d'])

In [11]:
print(A.values)
type(A.values)

[1 2 3 4]


numpy.ndarray

In [12]:
print(A.index)
type(A.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


pandas.core.indexes.base.Index

In [13]:
type(A)

pandas.core.series.Series

In [14]:
A['a':'c']

a    1
b    2
c    3
dtype: int64

In [35]:
grade_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grade_dict)
print(grades.values)
print(grades.index)
print(grades.index.values)
print(grades)

[4.  3.5 3.  2.5]
Index(['A', 'B', 'C', 'D'], dtype='object')
['A' 'B' 'C' 'D']
A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64


In [36]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)
print(marks.values)
print(marks.index)
print(marks.index.values)
print(marks)

[85 75 65 55]
Index(['A', 'B', 'C', 'D'], dtype='object')
['A' 'B' 'C' 'D']
A    85
B    75
C    65
D    55
dtype: int64


In [26]:
marks['A']

85

In [31]:
marks['A':'B']

A     85
A-    80
B     75
dtype: int64

In [32]:
marks[0:3]

A     85
A-    80
B     75
dtype: int64

# Pandas (Data Frame)

In [39]:
D = pd.DataFrame({'Marks':marks,'Grades':grades})

In [41]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [43]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [44]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [46]:
D.values[1][0]

75.0

In [47]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [48]:
D['Scaled Marks'] = 100 * (D['Marks']/90)

In [49]:
D

Marks  Grades  Scaled Marks
A     85     4.0     94.444444
B     75     3.5     83.333333
C     65     3.0     72.222222
D     55     2.5     61.111111

In [50]:
del D['Scaled Marks']

In [51]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

# Pandas (Indexing)

In [54]:
G = D[D['Marks']>70]

In [53]:
G

Marks  Grades
A     85     4.0
B     75     3.5

In [56]:
G = D[(D['Marks']>70) & (D['Marks']<80)]

In [57]:
G

Marks  Grades
B     75     3.5

# Pandas (NaN)

In [6]:
A = pd.DataFrame([{'a':1.0,'b':2.0,'c':3.0,'d':4.0},{'c':3.1,'d':4.1, 'e':5.0,'f':6.0}])

In [8]:
A

a    b    c    d    e    f
0  1.0  2.0  3.0  4.0  NaN  NaN
1  NaN  NaN  3.1  4.1  5.0  6.0

In [9]:
A.fillna(0)

a    b    c    d    e    f
0  1.0  2.0  3.0  4.0  0.0  0.0
1  0.0  0.0  3.1  4.1  5.0  6.0

In [11]:
# A.dropna