# Pandas

In [1]:
# Build on Top of Numpy
# Used for Data Manipulating, Data Cleaning, Data Preprocessing etc.

In [1]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

# Pandas (Series)

In [4]:
A = pd.Series([1,2,3,4],index=['a','b','c','d'])

In [11]:
print(A.values)
type(A.values)

[1 2 3 4]


numpy.ndarray

In [12]:
print(A.index)
type(A.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


pandas.core.indexes.base.Index

In [13]:
type(A)

pandas.core.series.Series

In [14]:
A['a':'c']

a    1
b    2
c    3
dtype: int64

In [36]:
grade_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grade_dict)
print(grades.values)
print(grades.index)
print(grades.index.values)
print(grades)

[4.  3.5 3.  2.5]
Index(['A', 'B', 'C', 'D'], dtype='object')
['A' 'B' 'C' 'D']
A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64


In [35]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)
print(marks.values)
print(marks.index)
print(marks.index.values)
print(marks)

[85 75 65 55]
Index(['A', 'B', 'C', 'D'], dtype='object')
['A' 'B' 'C' 'D']
A    85
B    75
C    65
D    55
dtype: int64


In [26]:
marks['A']

85

In [31]:
marks['A':'B']

A     85
A-    80
B     75
dtype: int64

In [32]:
marks[0:3]

A     85
A-    80
B     75
dtype: int64

# Pandas (Data Frame)

In [37]:
D = pd.DataFrame({'Marks':marks,'Grades':grades})

In [41]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [43]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [44]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [46]:
D.values[1][0]

75.0

In [47]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [48]:
D['Scaled Marks'] = 100 * (D['Marks']/90)

In [49]:
D

Marks  Grades  Scaled Marks
A     85     4.0     94.444444
B     75     3.5     83.333333
C     65     3.0     72.222222
D     55     2.5     61.111111

In [50]:
del D['Scaled Marks']

In [51]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

# Pandas (Indexing)

In [54]:
G = D[D['Marks']>70]

In [53]:
G

Marks  Grades
A     85     4.0
B     75     3.5

In [56]:
G = D[(D['Marks']>70) & (D['Marks']<80)]

In [57]:
G

Marks  Grades
B     75     3.5

# Pandas (NaN)

In [3]:
A = pd.DataFrame([{'a':1.0,'b':2.0,'c':3.0,'d':4.0},{'c':3.1,'d':4.1, 'e':5.0,'f':6.0}])

In [8]:
A

a    b    c    d    e    f
0  1.0  2.0  3.0  4.0  NaN  NaN
1  NaN  NaN  3.1  4.1  5.0  6.0

In [9]:
A.fillna(0)

a    b    c    d    e    f
0  1.0  2.0  3.0  4.0  0.0  0.0
1  0.0  0.0  3.1  4.1  5.0  6.0

In [52]:
A.dropna?

# Pandas (Indexing)

In [22]:
A = pd.Series(['a','b','c'],index=[1,3,5])

In [25]:
A[1]

'a'

In [26]:
# for Explicit Index
A.loc[1:3]

1    a
3    b
dtype: object

In [31]:
# for Implicit Index
A.iloc[0:3]

1    a
3    b
5    c
dtype: object

In [38]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [49]:
D.iloc[0,:]

Marks     85.0
Grades     4.0
Name: A, dtype: float64

In [51]:
D.iloc[::-1,:]

Marks  Grades
D     55     2.5
C     65     3.0
B     75     3.5
A     85     4.0

# Pandas (Reading CSV file)

In [2]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv('/home/abrar/Desktop/covid_19_data.csv');

In [5]:
df.rename(columns={'ObservationDate':'Date','Province/State':'State','Country/Region':'Country'},inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df.head(20)

SNo       Date           State         Country      Last Update  \
0     1 2020-01-22           Anhui  Mainland China  1/22/2020 17:00   
1     2 2020-01-22         Beijing  Mainland China  1/22/2020 17:00   
2     3 2020-01-22       Chongqing  Mainland China  1/22/2020 17:00   
3     4 2020-01-22          Fujian  Mainland China  1/22/2020 17:00   
4     5 2020-01-22           Gansu  Mainland China  1/22/2020 17:00   
5     6 2020-01-22       Guangdong  Mainland China  1/22/2020 17:00   
6     7 2020-01-22         Guangxi  Mainland China  1/22/2020 17:00   
7     8 2020-01-22         Guizhou  Mainland China  1/22/2020 17:00   
8     9 2020-01-22          Hainan  Mainland China  1/22/2020 17:00   
9    10 2020-01-22           Hebei  Mainland China  1/22/2020 17:00   
10   11 2020-01-22    Heilongjiang  Mainland China  1/22/2020 17:00   
11   12 2020-01-22           Henan  Mainland China  1/22/2020 17:00   
12   13 2020-01-22       Hong Kong       Hong Kong  1/22/2020 17:00   
13   14 2020-01-22           Hubei  Mainland China  1/22/2020 17:00   
14   15 2020-01-22           Hunan  Mainland China  1/22/2020 17:00   
15   16 2020-01-22  Inner Mongolia  Mainland China  1/22/2020 17:00   
16   17 2020-01-22         Jiangsu  Mainland China  1/22/2020 17:00   
17   18 2020-01-22         Jiangxi  Mainland China  1/22/2020 17:00   
18   19 2020-01-22           Jilin  Mainland China  1/22/2020 17:00   
19   20 2020-01-22        Liaoning  Mainland China  1/22/2020 17:00   

    Confirmed  Deaths  Recovered  
0         1.0     0.0        0.0  
1        14.0     0.0        0.0  
2         6.0     0.0        0.0  
3         1.0     0.0        0.0  
4         0.0     0.0        0.0  
5        26.0     0.0        0.0  
6         2.0     0.0        0.0  
7         1.0     0.0        0.0  
8         4.0     0.0        0.0  
9         1.0     0.0        0.0  
10        0.0     0.0        0.0  
11        5.0     0.0        0.0  
12        0.0     0.0        0.0  
13      444.0    17.0       28.0  
14        4.0     0.0        0.0  
15        0.0     0.0        0.0  
16        1.0     0.0        0.0  
17        2.0     0.0        0.0  
18        0.0     0.0        0.0  
19        2.0     0.0        0.0

In [8]:
imputer = SimpleImputer(strategy='constant')
df = pd.DataFrame(imputer.fit_transform(df),columns=df.columns)
df.head(20)

SNo       Date           State         Country      Last Update Confirmed  \
0    1 2020-01-22           Anhui  Mainland China  1/22/2020 17:00       1.0   
1    2 2020-01-22         Beijing  Mainland China  1/22/2020 17:00      14.0   
2    3 2020-01-22       Chongqing  Mainland China  1/22/2020 17:00       6.0   
3    4 2020-01-22          Fujian  Mainland China  1/22/2020 17:00       1.0   
4    5 2020-01-22           Gansu  Mainland China  1/22/2020 17:00       0.0   
5    6 2020-01-22       Guangdong  Mainland China  1/22/2020 17:00      26.0   
6    7 2020-01-22         Guangxi  Mainland China  1/22/2020 17:00       2.0   
7    8 2020-01-22         Guizhou  Mainland China  1/22/2020 17:00       1.0   
8    9 2020-01-22          Hainan  Mainland China  1/22/2020 17:00       4.0   
9   10 2020-01-22           Hebei  Mainland China  1/22/2020 17:00       1.0   
10  11 2020-01-22    Heilongjiang  Mainland China  1/22/2020 17:00       0.0   
11  12 2020-01-22           Henan  Mainland China  1/22/2020 17:00       5.0   
12  13 2020-01-22       Hong Kong       Hong Kong  1/22/2020 17:00       0.0   
13  14 2020-01-22           Hubei  Mainland China  1/22/2020 17:00     444.0   
14  15 2020-01-22           Hunan  Mainland China  1/22/2020 17:00       4.0   
15  16 2020-01-22  Inner Mongolia  Mainland China  1/22/2020 17:00       0.0   
16  17 2020-01-22         Jiangsu  Mainland China  1/22/2020 17:00       1.0   
17  18 2020-01-22         Jiangxi  Mainland China  1/22/2020 17:00       2.0   
18  19 2020-01-22           Jilin  Mainland China  1/22/2020 17:00       0.0   
19  20 2020-01-22        Liaoning  Mainland China  1/22/2020 17:00       2.0   

   Deaths Recovered  
0     0.0       0.0  
1     0.0       0.0  
2     0.0       0.0  
3     0.0       0.0  
4     0.0       0.0  
5     0.0       0.0  
6     0.0       0.0  
7     0.0       0.0  
8     0.0       0.0  
9     0.0       0.0  
10    0.0       0.0  
11    0.0       0.0  
12    0.0       0.0  
13   17.0      28.0  
14    0.0       0.0  
15    0.0       0.0  
16    0.0       0.0  
17    0.0       0.0  
18    0.0       0.0  
19    0.0       0.0

In [21]:
df.drop(['SNo','Last Update'],axis=1,inplace=True)

In [22]:
df.head(20)

Date           State         Country  Confirmed  Deaths  Recovered
0  2020-01-22           Anhui  Mainland China        1.0     0.0        0.0
1  2020-01-22         Beijing  Mainland China       14.0     0.0        0.0
2  2020-01-22       Chongqing  Mainland China        6.0     0.0        0.0
3  2020-01-22          Fujian  Mainland China        1.0     0.0        0.0
4  2020-01-22           Gansu  Mainland China        0.0     0.0        0.0
5  2020-01-22       Guangdong  Mainland China       26.0     0.0        0.0
6  2020-01-22         Guangxi  Mainland China        2.0     0.0        0.0
7  2020-01-22         Guizhou  Mainland China        1.0     0.0        0.0
8  2020-01-22          Hainan  Mainland China        4.0     0.0        0.0
9  2020-01-22           Hebei  Mainland China        1.0     0.0        0.0
10 2020-01-22    Heilongjiang  Mainland China        0.0     0.0        0.0
11 2020-01-22           Henan  Mainland China        5.0     0.0        0.0
12 2020-01-22       Hong Kong       Hong Kong        0.0     0.0        0.0
13 2020-01-22           Hubei  Mainland China      444.0    17.0       28.0
14 2020-01-22           Hunan  Mainland China        4.0     0.0        0.0
15 2020-01-22  Inner Mongolia  Mainland China        0.0     0.0        0.0
16 2020-01-22         Jiangsu  Mainland China        1.0     0.0        0.0
17 2020-01-22         Jiangxi  Mainland China        2.0     0.0        0.0
18 2020-01-22           Jilin  Mainland China        0.0     0.0        0.0
19 2020-01-22        Liaoning  Mainland China        2.0     0.0        0.0

In [11]:
df.describe()

Date     Confirmed       Deaths     Recovered
count                           4247   4247.000000  4247.000000   4247.000000
mean   2020-02-19 20:20:37.579467776    586.884624    17.530257    187.914528
min              2020-01-22 00:00:00      0.000000     0.000000      0.000000
25%              2020-02-09 00:00:00      1.000000     0.000000      0.000000
50%              2020-02-23 00:00:00      9.000000     0.000000      1.000000
75%              2020-03-03 00:00:00     99.500000     1.000000     16.000000
max              2020-03-08 00:00:00  67707.000000  2986.000000  45235.000000
std                              NaN   5033.596411   190.278672   1976.388824

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4247 entries, 0 to 4246
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   Date       4247 non-null   datetime64[ns]
 1   State      2746 non-null   object        
 2   Country    4247 non-null   object        
 3   Confirmed  4247 non-null   float64       
 4   Deaths     4247 non-null   float64       
 5   Recovered  4247 non-null   float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 199.2+ KB


In [14]:
%%timeit
sum = 0
for d in df['Deaths']:
    sum+=d
sum

174 µs ± 2.93 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [15]:
%%timeit 
tDeaths = df['Deaths'].sum()
tDeaths

10.9 µs ± 23.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [34]:
df.fillna('NA',inplace=True)

In [37]:
df[df['State'] == 'NA']

Date State       Country  Confirmed  Deaths  Recovered
35   2020-01-22    NA         Japan        2.0     0.0        0.0
36   2020-01-22    NA      Thailand        2.0     0.0        0.0
37   2020-01-22    NA   South Korea        1.0     0.0        0.0
73   2020-01-23    NA         Japan        1.0     0.0        0.0
74   2020-01-23    NA      Thailand        3.0     0.0        0.0
...         ...   ...           ...        ...     ...        ...
4183 2020-03-08    NA        Serbia        1.0     0.0        0.0
4184 2020-03-08    NA     Sri Lanka        1.0     0.0        1.0
4185 2020-03-08    NA          Togo        1.0     0.0        0.0
4239 2020-03-08    NA       Ukraine        1.0     0.0        0.0
4240 2020-03-08    NA  Vatican City        1.0     0.0        0.0

[1501 rows x 6 columns]

In [39]:
df.head(20)

Date           State         Country  Confirmed  Deaths  Recovered
0  2020-01-22           Anhui  Mainland China        1.0     0.0        0.0
1  2020-01-22         Beijing  Mainland China       14.0     0.0        0.0
2  2020-01-22       Chongqing  Mainland China        6.0     0.0        0.0
3  2020-01-22          Fujian  Mainland China        1.0     0.0        0.0
4  2020-01-22           Gansu  Mainland China        0.0     0.0        0.0
5  2020-01-22       Guangdong  Mainland China       26.0     0.0        0.0
6  2020-01-22         Guangxi  Mainland China        2.0     0.0        0.0
7  2020-01-22         Guizhou  Mainland China        1.0     0.0        0.0
8  2020-01-22          Hainan  Mainland China        4.0     0.0        0.0
9  2020-01-22           Hebei  Mainland China        1.0     0.0        0.0
10 2020-01-22    Heilongjiang  Mainland China        0.0     0.0        0.0
11 2020-01-22           Henan  Mainland China        5.0     0.0        0.0
12 2020-01-22       Hong Kong       Hong Kong        0.0     0.0        0.0
13 2020-01-22           Hubei  Mainland China      444.0    17.0       28.0
14 2020-01-22           Hunan  Mainland China        4.0     0.0        0.0
15 2020-01-22  Inner Mongolia  Mainland China        0.0     0.0        0.0
16 2020-01-22         Jiangsu  Mainland China        1.0     0.0        0.0
17 2020-01-22         Jiangxi  Mainland China        2.0     0.0        0.0
18 2020-01-22           Jilin  Mainland China        0.0     0.0        0.0
19 2020-01-22        Liaoning  Mainland China        2.0     0.0        0.0

In [46]:
df2 = df.groupby('Country')[['Confirmed','Deaths','Recovered']].sum().reset_index()

In [49]:
df2.head(20)

Country  Confirmed  Deaths  Recovered
0               Azerbaijan        1.0     0.0        0.0
1              Afghanistan       17.0     0.0        0.0
2                  Algeria       91.0     0.0        0.0
3                  Andorra        7.0     0.0        0.0
4                Argentina       25.0     1.0        0.0
5                  Armenia        8.0     0.0        0.0
6                Australia      929.0    15.0      327.0
7                  Austria      380.0     0.0        0.0
8               Azerbaijan       42.0     0.0        0.0
9                  Bahrain      649.0     0.0       12.0
10              Bangladesh        3.0     0.0        0.0
11                 Belarus       35.0     0.0        0.0
12                 Belgium      600.0     0.0       21.0
13                  Bhutan        3.0     0.0        0.0
14  Bosnia and Herzegovina       10.0     0.0        0.0
15                  Brazil       65.0     0.0        0.0
16                Bulgaria        4.0     0.0        0.0
17                Cambodia       43.0     0.0       26.0
18                Cameroon        4.0     0.0        0.0
19                  Canada      564.0     0.0       97.0

In [10]:
df2 = df.groupby(['Country','Date'])[['Confirmed','Deaths','Recovered']].sum().reset_index()

In [54]:
df2.head(20)

Country       Date  Confirmed  Deaths  Recovered
0    Azerbaijan 2020-02-28        1.0     0.0        0.0
1   Afghanistan 2020-02-24        1.0     0.0        0.0
2   Afghanistan 2020-02-25        1.0     0.0        0.0
3   Afghanistan 2020-02-26        1.0     0.0        0.0
4   Afghanistan 2020-02-27        1.0     0.0        0.0
5   Afghanistan 2020-02-28        1.0     0.0        0.0
6   Afghanistan 2020-02-29        1.0     0.0        0.0
7   Afghanistan 2020-03-01        1.0     0.0        0.0
8   Afghanistan 2020-03-02        1.0     0.0        0.0
9   Afghanistan 2020-03-03        1.0     0.0        0.0
10  Afghanistan 2020-03-04        1.0     0.0        0.0
11  Afghanistan 2020-03-05        1.0     0.0        0.0
12  Afghanistan 2020-03-06        1.0     0.0        0.0
13  Afghanistan 2020-03-07        1.0     0.0        0.0
14  Afghanistan 2020-03-08        4.0     0.0        0.0
15      Algeria 2020-02-25        1.0     0.0        0.0
16      Algeria 2020-02-26        1.0     0.0        0.0
17      Algeria 2020-02-27        1.0     0.0        0.0
18      Algeria 2020-02-28        1.0     0.0        0.0
19      Algeria 2020-02-29        1.0     0.0        0.0

In [11]:
df2[df2['Confirmed'] > 100]

Country       Date Confirmed Deaths Recovered
106   Austria 2020-03-08     104.0    0.0       0.0
171   Belgium 2020-03-06     109.0    0.0       1.0
172   Belgium 2020-03-07     169.0    0.0       1.0
173   Belgium 2020-03-08     200.0    0.0       1.0
461    France 2020-03-01     130.0    2.0      12.0
...       ...        ...       ...    ...       ...
1761       US 2020-03-04     153.0   11.0       8.0
1762       US 2020-03-05     221.0   12.0       8.0
1763       US 2020-03-06     278.0   14.0       8.0
1764       US 2020-03-07     417.0   17.0       8.0
1765       US 2020-03-08     537.0   21.0       8.0

[202 rows x 5 columns]